//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadTex_MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole_Permission
    {
        public int role_permission_id { get; set; }
        public int role_id { get; set; }
        public int perm_id { get; set; }
        public bool edit_perm { get; set; }
        public bool view_perm { get; set; }
    
        public virtual tblPermission tblPermission { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
